#!/bin/bash
cython -3 --embed asteg.py
gcc -Os -I/usr/include/python3.6 asteg.c -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6 -o asteg

#Compiling for windows
#NOT WORKING on Linux. Needed python library for windows
#i686-w64-mingw32-gcc -Os -I/usr/include/python3.6 asteg.c -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6 -o asteg.exe

rm asteg.c
chmod +x asteg

